# Generated by Django 6.0.3 on 2026-03-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ENTRADAS', 'Entradas'), ('SOPAS', 'Sopas'), ('CARNE', 'Carne'), ('PEIXE', 'Peixe'), ('SOBREMESA', 'Sobremesa')], max_length=20)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('status', models.CharField(choices=[('ORDER_PREVIEW', 'Order Preview'), ('PREPARING', 'Preparing'), ('COOLING_DOWN', 'Cooling Down'), ('READY_TO_SERVE', 'Ready to Serve'), ('CONCLUDED', 'Concluded')], default='ORDER_PREVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
